from django.db import models
from django.db.models import Model




class Rcolabb(models.Model):
    username = models.CharField(max_length=50)
    iphone13promax= models.IntegerField(default=0,primary_key=False)
    iphone12promax= models.IntegerField(default=0,primary_key=False)
    iphone11pro= models.IntegerField(default=0,primary_key=False)
    iphoneSE= models.IntegerField(default=0,primary_key=False)
    iphoneX= models.IntegerField(default=0,primary_key=False)
    SamsungGalaxyA52= models.IntegerField(default=0,primary_key=False)
    SamsungGalaxyS20= models.IntegerField(default=0,primary_key=False)
    SamsungGalaxyM32= models.IntegerField(default=0,primary_key=False)
    SamsungGalaxyM12= models.IntegerField(default=0,primary_key=False)
    SamsungGalaxyF22= models.IntegerField(default=0,primary_key=False)
    Oneplus10pro= models.IntegerField(default=0,primary_key=False)
    Oneplus9R= models.IntegerField(default=0,primary_key=False)
    OneplusNord= models.IntegerField(default=0,primary_key=False)
    Oneplus8T= models.IntegerField(default=0,primary_key=False)
    Oneplus7= models.IntegerField(default=0,primary_key=False)
    Redminote11= models.IntegerField(default=0,primary_key=False)
    Redminote10= models.IntegerField(default=0,primary_key=False)
    Redmi9A= models.IntegerField(default=0,primary_key=False)
    Redmi8A= models.IntegerField(default=0,primary_key=False)
    Redmi7A= models.IntegerField(default=0,primary_key=False)
    DellVostro= models.IntegerField(default=0,primary_key=False)
    DellInspiron= models.IntegerField(default=0,primary_key=False)
    HpRyzen= models.IntegerField(default=0,primary_key=False)
    HpEnvy= models.IntegerField(default=0,primary_key=False)
    Applemacbookair= models.IntegerField(default=0,primary_key=False)
    Applemacbookpro= models.IntegerField(default=0,primary_key=False)
    ASUSzenbook= models.IntegerField(default=0,primary_key=False)
    Asusvivobook= models.IntegerField(default=0,primary_key=False)
    Lenevoideapadslim5= models.IntegerField(default=0,primary_key=False)
    Lenevoideapadslim3= models.IntegerField(default=0,primary_key=False)
    Samsungrefrigerator= models.IntegerField(default=0,primary_key=False)
    Haierrefrigerator= models.IntegerField(default=0,primary_key=False)
    Whirpoolrefrigerator= models.IntegerField(default=0,primary_key=False)
    Amazonbasicrefrigerator= models.IntegerField(default=0,primary_key=False)
    LGrefrigerator= models.IntegerField(default=0,primary_key=False)
    BlustarAC= models.IntegerField(default=0,primary_key=False)
    SamsungAC= models.IntegerField(default=0,primary_key=False)
    HaierAC= models.IntegerField(default=0,primary_key=False)
    WhirpoolAC= models.IntegerField(default=0,primary_key=False)
    AmazonbasicAC= models.IntegerField(default=0,primary_key=False)
    HavellsTrimmer= models.IntegerField(default=0,primary_key=False)
    NovaTrimmer= models.IntegerField(default=0,primary_key=False)
    SYSKATrimmer= models.IntegerField(default=0,primary_key=False)
    PhilipsTrimmer= models.IntegerField(default=0,primary_key=False)
    MITrimmer= models.IntegerField(default=0,primary_key=False)
    AppleAirpods= models.IntegerField(default=0,primary_key=False)
    OneplusBuds= models.IntegerField(default=0,primary_key=False)
    NoiseAirbuds= models.IntegerField(default=0,primary_key=False)
    boatairdopes= models.IntegerField(default=0,primary_key=False)
    Jblairbuds= models.IntegerField(default=0,primary_key=False)
    OneplusTv= models.IntegerField(default=0,primary_key=False)
    LGTv= models.IntegerField(default=0,primary_key=False)
    SonyTv= models.IntegerField(default=0,primary_key=False)
    SamsungTv= models.IntegerField(default=0,primary_key=False)
    RedmiTv= models.IntegerField(default=0,primary_key=False)
    SonySoundbar= models.IntegerField(default=0,primary_key=False)
    PanasonicSpeaker= models.IntegerField(default=0,primary_key=False)
    Philipsspeaker= models.IntegerField(default=0,primary_key=False)
    Zebronicssubwoofer= models.IntegerField(default=0,primary_key=False)
    Ahujaspeaker= models.IntegerField(default=0,primary_key=False)
    Boatsmartwatch= models.IntegerField(default=0,primary_key=False)
    Firebolttsmartwatch= models.IntegerField(default=0,primary_key=False)
    Marviksmartwatch= models.IntegerField(default=0,primary_key=False)
    Noisesmartwatch= models.IntegerField(default=0,primary_key=False)
    Genericsmartwatch= models.IntegerField(default=0,primary_key=False)
    Applesmartwatch= models.IntegerField(default=0,primary_key=False)
    Mismartwatch= models.IntegerField(default=0,primary_key=False)
    Fitbitsmartwatch= models.IntegerField(default=0,primary_key=False)
    Amazfitsmartwatch= models.IntegerField(default=0,primary_key=False)
    Oneplussmartwatch= models.IntegerField(default=0,primary_key=False)


    def __str__(self):
        return self.username

class Rcolabclass(models.Model):
    id = models.IntegerField(default=0,primary_key=True)
    title = models.CharField(max_length=50)
    tag = models.CharField(max_length=300)
    image = models.ImageField(upload_to='uploads/recproducts')
