from django.urls import path

from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path('login/',views.loginview,name='login'),
    path('userhome/',views.userhomeview,name='userhome'),
    path('signup/',views.signupview,name='signup'),
    path('cloth/',views.clothview,name='cloth'),
    path('groc/',views.grocview,name='groc'),
    path('elec/',views.elecview,name='elec'),
    path('cloth2/',views.clothuserview,name='cloth2'),
    path('groc2/',views.grocuserview,name='groc2'),
    path('elec2/',views.elecuserview,name='elec2'),
    path('cart/',views.cartview,name='cart'),
    path('signup/register',views.registerview,name='register'),
    path('login/loginpage',views.loginpageview,name='loginpage'),
    path('logoutmypage/',views.logoutmypageview,name='logoutmypage'),
    path('cloth2/addtocart',views.addtocartview,name='addtocart'),
    path('cloth2/removefromcart',views.removefromcartview,name='removefromcart'),
    path('groc2/addtocartg',views.addtocartviewg,name='addtocartg'),
    path('groc2/removefromcartg',views.removefromcartviewg,name='removefromcartg'),
    path('elec2/addtocarte',views.addtocartviewe,name='addtocarte'),
    path('elec2/removefromcarte',views.removefromcartviewe,name='removefromcarte'),

    path('elec2/e1/<int:id>',views.e1view,name='e1'),
    path('elec2/e2/<int:id>',views.e2view,name='e2'),
    path('elec2/e3/<int:id>',views.e3view,name='e3'),
    path('elec2/e4/<int:id>',views.e4view,name='e4'),
    path('elec2/e5/<int:id>',views.e5view,name='e5'),
    path('elec2/e6/<int:id>',views.e6view,name='e6'),
    path('elec2/e7/<int:id>',views.e7view,name='e7'),
    path('elec2/e8/<int:id>',views.e8view,name='e8'),
    path('elec2/e9/<int:id>',views.e9view,name='e9'),
    path('elec2/e10/<int:id>',views.e10view,name='e10'),
    path('elec2/e11/<int:id>',views.e11view,name='e11'),
    path('elec2/e12/<int:id>',views.e12view,name='e12'),
    path('elec2/e13/<int:id>',views.e13view,name='e13'),
    path('elec2/e14/<int:id>',views.e14view,name='e14'),
    path('elec2/e15/<int:id>',views.e15view,name='e15'),
    path('elec2/e16/<int:id>',views.e16view,name='e16'),

    path('terms/',views.termsview,name='terms'),
    path('about/',views.aboutview,name='about'),
    path('contact/',views.contactview,name='contact'),
    path('help/',views.helpview,name='help'),
    path('terms2/',views.termsviewu,name='terms2'),
    path('about2/',views.aboutviewu,name='about2'),
    path('contact2/',views.contactviewu,name='contact2'),
    path('help2/',views.helpviewu,name='help2'),
    path('helpresult/',views.helpresultview,name='helpresult'),


    path('elec2/e1/ratenowe1/',views.ratnowviewe1,name='ratenowe1'),
    path('elec2/e2/ratenowe2/',views.ratnowviewe2,name='ratenowe2'),
    path('elec2/e3/ratenowe3/',views.ratnowviewe3,name='ratenowe3'),
    path('elec2/e4/ratenowe4/',views.ratnowviewe4,name='ratenowe4'),
    path('elec2/e5/ratenowe5/',views.ratnowviewe5,name='ratenowe5'),
    path('elec2/e6/ratenowe6/',views.ratnowviewe6,name='ratenowe6'),
    path('elec2/e7/ratenowe7/',views.ratnowviewe7,name='ratenowe7'),
    path('elec2/e8/ratenowe8/',views.ratnowviewe8,name='ratenowe8'),
    path('elec2/e9/ratenowe9/',views.ratnowviewe9,name='ratenowe9'),
    path('elec2/e10/ratenowe10/',views.ratnowviewe10,name='ratenowe10'),
    path('elec2/e11/ratenowe11/',views.ratnowviewe11,name='ratenowe11'),
    path('elec2/e12/ratenowe12/',views.ratnowviewe12,name='ratenowe12'),
    path('elec2/e13/ratenowe13/',views.ratnowviewe13,name='ratenowe13'),
    path('elec2/e14/ratenowe14/',views.ratnowviewe14,name='ratenowe14'),
    path('elec2/e15/ratenowe15/',views.ratnowviewe15,name='ratenowe15'),
    path('elec2/e16/ratenowe16/',views.ratnowviewe16,name='ratenowe16'),
    path('export/',views.exportview,name='export'),

]
